### ISSUE TITLE
Unable to configure DIX & MD pools through CDF file

### ISSUE THREAD

**Issue by yatin-mahajan** [Seagate/cortx-hare#1242]
Getting **" 'dict' object has no attribute 'data_units' "** error on hctl bootstrap with CDF file which has Dix & md pool cofing mention. 
```
[root@ssc-vm-0378 cortx-hare]# hctl bootstrap --mkfs cfgen/examples/singlenode.yaml
2020-08-31 05:05:38: Generating cluster configuration...Traceback (most recent call last):
  File "/opt/seagate/cortx/hare/bin/cfgen", line 1504, in <module>
    main()
  File "/opt/seagate/cortx/hare/bin/cfgen", line 121, in main
    validate_cluster_desc(cluster_desc)
  File "/opt/seagate/cortx/hare/bin/cfgen", line 278, in validate_cluster_desc
    assert pool.data_units == 1, f"""\
AttributeError: 'dict' object has no attribute 'data_units'
```

Here is my CDF file. 
```
[root@ssc-vm-0378 cortx-hare]# cat cfgen/examples/singlenode.yaml
# Cluster Description File (CDF).
# See `cfgen --help-schema` for the format description.

nodes:
  - hostname: ssc-vm-0378.colo.seagate.com     # [user@]hostname
    data_iface: eth0        # name of data network interface
    #data_iface_type: o2ib  # type of network interface (optional);
                            # supported values: "tcp" (default), "o2ib"
    m0_servers:
      - runs_confd: true
        io_disks:
          data: []
      - io_disks:
          data:
            - /dev/loop1
            - /dev/loop2
      - io_disks:
          data:
            - /dev/loop3
            - /dev/loop4
      - io_disks:
          data:
            - /dev/loop5
            - /dev/loop6
      - io_disks:
          data:
            - /dev/loop7
            - /dev/loop8
    m0_clients:
      s3: 0         # number of S3 servers to start
      other: 2      # max quantity of other Motr clients this host may have
pools:
  - name: the pool
    type: sns  # optional; supported values: "sns" (default), "dix", "md"
    data_units: 2
    parity_units: 1
    #allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
  - name: DIX pool
    type: dix  # optional; supported values: "sns" (default), "dix", "md"
    data_units: 1
    parity_units: 1
    #allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
  - name: MD pool
    type: sns  # optional; supported values: "sns" (default), "dix", "md"
    data_units: 1
    parity_units: 0
    #allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
```

However I was able to bootstrap with below workaround in cfgen/cfgen 
```
[root@ssc-vm-0378 cortx-hare]# git diff cfgen/cfgen
diff --git a/cfgen/cfgen b/cfgen/cfgen
index 5d9440a..061ce3c 100755
--- a/cfgen/cfgen
+++ b/cfgen/cfgen
@@ -275,7 +275,7 @@ Make sure the value of data_iface in the CDF is correct."""
 The number of allowed disk failures must not exceed the number of spare disks\
  (parity_units={}).""".format(name, d['disk'], pool['parity_units'])
         else:
-            assert pool.data_units == 1, f"""\
+            assert pool['data_units'] == 1, f"""\
 {name}: Wrong number of data_units ({pool.data_units})
 Pools of {t!r} type can only have 1 data unit."""
             assert t not in pool_types, \

```
