### ISSUE TITLE
[Mini Provisioner] Arguments like '--config' or '--init' should be just 'config' and 'init' respectively

### ISSUE THREAD

**Issue by knekrasov** [Seagate/cortx-hare#1482]
In current implementation the hare_setup CLI looks as follows:

```yaml
hare:
  post_install:
    script: /opt/seagate/cortx/hare/bin/hare_setup
    args: --report-unavailable-features --post_install
  init:
    script: /opt/seagate/cortx/hare/bin/hare_setup
    args: --init
  config:
    script: /opt/seagate/cortx/hare/bin/hare_setup
    args: --config $URL --filename '/var/lib/hare/cluster.yaml'
  test:
    script: /opt/seagate/cortx/hare/bin/hare_setup
    args: --test
  support_bundle:
    script: /opt/seagate/cortx/hare/bin/hare_setup
    args: --support_bundle
  reset:
    script: /opt/seagate/cortx/hare/bin/hare_setup
    args: --reset
  cleanup:
    script: /opt/seagate/cortx/hare/bin/hare_setup
    args: --cleanup
```

Things that are supposed to be subcommands look like flags. More than that, it doesn't fully correspond to [Mini-Provisioner Specifications](https://seagatetechnology.sharepoint.com/:w:/r/sites/gteamdrv1/tdrive1224/_layouts/15/Doc.aspx?sourcedoc=%7B41048EAD-3E48-4163-B9CC-69A04FE7E67B%7D&file=Mini-Provisioner%20Specifications.docx&nav=eyJjIjo2NDgwNzEzNDB9&action=default&mobileredirect=true) document and thus should be changed.

Switching this CLI to a concept of sub-commands can simplify processing of some optional parameters (like `--filename` - to specify CDF file for `init` command).

Suggested approaches:
1. [Subparsers](https://docs.python.org/3/library/argparse.html#sub-commands) in argparse (this is the library we use nowadays). Maybe quite wordy, though.
2. Switch to [Click library](https://click.palletsprojects.com/en/7.x/commands/) and use their multicommands.
