### ISSUE TITLE
cfgen: wrong md and dix pools with client nodes in CDF

### ISSUE THREAD

**Issue by andriytk** [Seagate/cortx-hare#1794]
When pure client nodes are present in the cluster configuration (which do not have `m0_servers` section), cfgen generates invalid tolerance vector and invalind parameters for dix and md pools, so that `m0mkfs` fails:

```
Sep 15 17:21:35 cmu motr-mkfs[23769]: + exec /usr/sbin/m0mkfs -e lnet:192.168.180.176@tcp:12345:2:1 -A linuxstob:addb-stobs -f '<0x7200000000000001:0x9>' -T linux -S stobs -D db -m 524288 -q 16 -c /etc/motr/confd.xc -H 192.168.180.176@tcp:12345:1:1 -U -F -u 9638113e-160b-11ec-89c1-000c29b5b2ac -z 8589934592 -r 1073741824
Sep 15 17:21:36 cmu motr-mkfs[23769]: motr[23771]:  7b30  ERROR  [layout/pdclust.c:348:m0_pdclust_attr_check]  Bad pdclust attributes (P < N+K+S and S=0 or S==K): P=1 N=1 K=1 S=0
Sep 15 17:21:36 cmu motr-mkfs[23769]: motr[23771]:  7bc0  ERROR  [conf/obj_ops.c:75:_concrete_obj_invariant]  Configuration object invariant does not hold: id=<7600000000000001:3b>
Sep 15 17:21:36 cmu motr-mkfs[23769]: motr[23771]:  7ad0  FATAL  [lib/assert.c:50:m0_panic]  panic: ((!(rc == 0) || (m0_conf_obj_invariant(dest)))) at m0_conf_obj_fill() (conf/obj_ops.c:249) m0_pdclust_attr_check( &self->pv_u.subtree.pvs_attr) [git: 2.0.0-307-20-g46ab3c2] /var/motr/m0d-0x7200000000000001:0x9/m0trace.23771
```

Here is the CDF example:

```
nodes:
  - hostname: cmu # [user@]hostname
    data_iface: eth0        # name of data network interface
    m0_servers:
      - runs_confd: true
        io_disks:
          data: []
      - io_disks:
          data:
            - /dev/loop0
            - /dev/loop1
            - /dev/loop2
            - /dev/loop3
    m0_clients:
      s3: 0                # number of S3 servers to start
      other: 2             # max number of other Motr clients this host may have
  - hostname: client  # [user@]hostname
    data_iface: eth0        # name of data network interface
    m0_clients:
      s3: 0                # number of S3 servers to start
      other: 2
pools:
  - name: the pool
    data_units: 1
    parity_units: 0
```

Here are the pool versions generated:

```
[root@cmu ~]# m0confgen -f xcode -t confgen /etc/motr/confd.xc | grep pver-
(root-0 verno=1 rootfid=root-0 mdpool=pool-65 imeta_pver=pver-59 mdredundancy=2 params=[] nodes=[node-3, node-35] sites=[site-1] pools=[pool-46, pool-56, pool-65] profiles=[profile-72] fdmi_flt_grps=[])
(site-1 racks=[rack-2] pvers=[pver-47, pver-59, pver-66])
(rack-2 encls=[enclosure-4, enclosure-36] pvers=[pver-47, pver-59, pver-66])
(enclosure-4 node=node-3 ctrls=[controller-5] pvers=[pver-47, pver-59, pver-66])
(controller-5 drives=[drive-16, drive-18, drive-20, drive-22, drive-58] pvers=[pver-47, pver-59, pver-66])
(drive-16 dev=sdev-15 pvers=[pver-47, pver-66])
(drive-18 dev=sdev-17 pvers=[pver-47])
(drive-20 dev=sdev-19 pvers=[pver-47])
(drive-22 dev=sdev-21 pvers=[pver-47])
(pool-46 pver_policy=0 pvers=[pver-47])
(pver-47 N=1 K=0 S=0 P=4 tolerance=[0, 0, 0, 0, 0] sitevs=[objv-52])
(pool-56 pver_policy=0 pvers=[pver-59])
(drive-58 dev=sdev-57 pvers=[pver-59])
(pver-59 N=1 K=1 S=0 P=1 tolerance=[0, 0, 1, 0, 1] sitevs=[objv-64])
(pool-65 pver_policy=0 pvers=[pver-66])
(pver-66 N=1 K=1 S=0 P=1 tolerance=[0, 0, 1, 0, 1] sitevs=[objv-71])
```

Compare with the pool versions of the singlenode cluster configuration:

```
[root@cmu ~]# m0confgen -f xcode -t confgen /etc/motr/confd.xc | grep pver-
(root-0 verno=1 rootfid=root-0 mdpool=pool-54 imeta_pver=pver-48 mdredundancy=1 params=[] nodes=[node-3] sites=[site-1] pools=[pool-35, pool-45, pool-54] profiles=[profile-61] fdmi_flt_grps=[])
(site-1 racks=[rack-2] pvers=[pver-36, pver-48, pver-55])
(rack-2 encls=[enclosure-4] pvers=[pver-36, pver-48, pver-55])
(enclosure-4 node=node-3 ctrls=[controller-5] pvers=[pver-36, pver-48, pver-55])
(controller-5 drives=[drive-16, drive-18, drive-20, drive-22, drive-47] pvers=[pver-36, pver-48, pver-55])
(drive-16 dev=sdev-15 pvers=[pver-36, pver-55])
(drive-18 dev=sdev-17 pvers=[pver-36])
(drive-20 dev=sdev-19 pvers=[pver-36])
(drive-22 dev=sdev-21 pvers=[pver-36])
(pool-35 pver_policy=0 pvers=[pver-36])
(pver-36 N=1 K=0 S=0 P=4 tolerance=[0, 0, 0, 0, 0] sitevs=[objv-41])
(pool-45 pver_policy=0 pvers=[pver-48])
(drive-47 dev=sdev-46 pvers=[pver-48])
(pver-48 N=1 K=0 S=0 P=1 tolerance=[0, 0, 0, 0, 0] sitevs=[objv-53])
(pool-54 pver_policy=0 pvers=[pver-55])
(pver-55 N=1 K=0 S=0 P=1 tolerance=[0, 0, 0, 0, 0] sitevs=[objv-60])
```

Looks like the pure client node represented as an enclosure, and it is included in calculation of K for dix and md pools - which is wrong.
