### ISSUE TITLE
Problem: cfgen not able to retrieve drive facts if hostname is other than localhost

### ISSUE THREAD

**Issue by rajanikantchirmade** [Seagate/cortx-hare#207]
cfgen not able to retrieve drive facts without --mock option if hostname is other than localhost

Cluster configuration file for single node is as below :

```
hosts:
  - name: cmu
    m0_servers:
      - runs_confd: true
      - io_disks: { path_glob: "/dev/loop[0-9]*" }
    c0_clients: 2
    m0t1fs_clients: 0
pools:
  - name: the pool
    disks: all
    data_units: 1
    parity_units: 0
    # allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
```
