### ISSUE TITLE
Problem: bootstrap fails if host names are canonical (FQDN)

### ISSUE THREAD

**Issue by just-now** [Seagate/cortx-hare#627]
Steps to reproduce:
1. Go to machine with at least one dot in `$HOSTNAME`
   (e.g., `skln3-m04.mero.colo.seagate.com` or `eos-democ-103.mero.colo.seagate.com`).
2. Try to bootstrap single-node setup, following instructions in [`README_developers.md`](README_developers.md).

---

```
$ echo $HOSTNAME
skln3-m04.mero.colo.seagate.com
```

Cluster description file:
```
skln3-m04@hare git:(master)$ cat /root/anatoliy/configs/cdf.yaml
nodes:
  - hostname: skln3-m04.mero.colo.seagate.com
    data_iface: bond0
    m0_servers:
      - runs_confd: true
      - io_disks: { path_glob: "/dev/mapper/mpath[klm]" }
      - io_disks: { path_glob: "/dev/mapper/mpath[pqr]" }
    m0_clients:
        s3: 0
        other: 2
pools:
  - name: the pool
    disks: all
    data_units: 1
    parity_units: 0
    # allowed_failures: { site: 0, rack: 0, encl: 0, ctrl: 0, disk: 0 }
```

The bootstrap fails (note the lines marked with :point_right:):
```
$ hctl bootstrap --mkfs /root/anatoliy/configs/cdf.yaml
+ export 'PS4=+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
+ PS4='+ [${BASH_SOURCE[0]##*/}:${LINENO}${FUNCNAME[0]:+:${FUNCNAME[0]}}] '
+ [hare-bootstrap:8] PROG=hare-bootstrap
++ [hare-bootstrap:86] getopt --options hc: --longoptions help,mkfs,conf-dir: --name hare-bootstrap -- --mkfs /root/anatoliy/configs/cdf.yaml
+ [hare-bootstrap:86] TEMP=' --mkfs -- '\''/root/anatoliy/configs/cdf.yaml'\'''
+ [hare-bootstrap:88] (( 0 == 0 ))
+ [hare-bootstrap:90] eval set -- ' --mkfs -- '\''/root/anatoliy/configs/cdf.yaml'\'''
++ [hare-bootstrap:90] set -- --mkfs -- /root/anatoliy/configs/cdf.yaml
+ [hare-bootstrap:92] conf_dir=
+ [hare-bootstrap:93] opt_mkfs=
+ [hare-bootstrap:95] true
+ [hare-bootstrap:96] case "$1" in
+ [hare-bootstrap:98] opt_mkfs=--mkfs
+ [hare-bootstrap:98] shift
+ [hare-bootstrap:95] true
+ [hare-bootstrap:96] case "$1" in
+ [hare-bootstrap:100] shift
+ [hare-bootstrap:100] break
+ [hare-bootstrap:105] [[ -n '' ]]
+ [hare-bootstrap:105] (( 1 == 1 ))
+ [hare-bootstrap:110] cluster_descr=/root/anatoliy/configs/cdf.yaml
+ [hare-bootstrap:111] cfgen_out=/var/lib/hare
+ [hare-bootstrap:113] sudo systemctl --quiet is-active hare-consul-agent
+ [hare-bootstrap:117] [[ -n '' ]]
+ [hare-bootstrap:118] say 'Generating cluster configuration... '
++ [hare-bootstrap:31:say] date '+%F %T'
+ [hare-bootstrap:31:say] echo -n '2020-01-20 02:07:57: Generating cluster configuration... '
2020-01-20 02:07:57: Generating cluster configuration... + [hare-bootstrap:119] cfgen -o /var/lib/hare /root/anatoliy/configs/cdf.yaml
+ [hare-bootstrap:120] sudo mkdir -p /etc/mero
+ [hare-bootstrap:121] dhall text
+ [hare-bootstrap:121] m0confgen
+ [hare-bootstrap:122] echo Ok.
Ok.
+ [hare-bootstrap:126] read _ join_ip
++ [hare-bootstrap:126] get_server_nodes
👉++ [hare-bootstrap:126] grep -w skln3-m04.mero.colo.seagate.com
++ [hare-bootstrap:35:get_server_nodes] jq -r '.servers[] | "\(.hostname) \(.ipaddr)"' /var/lib/hare/consul-agents.json
+ [hare-bootstrap:128] [[ -n '' ]]
+ [hare-bootstrap:129] echo 'Bootstrap should be run from the server node only'
Bootstrap should be run from the server node only
+ [hare-bootstrap:130] exit 1
👉$ cat /var/lib/hare/consul-agents.json
{
  "servers": [
    {
👉    "hostname": "skln3-m04",
      "ipaddr": "172.16.0.133"
    }
  ],
  "clients": []
}
```
