### ISSUE TITLE
Problem: invalid YAML in setup-ha.yaml

### ISSUE THREAD

**Issue by vvv** [Seagate/cortx-hare#741]
This particular [snippet](https://github.com/Seagate/hare/blob/master/provisioning/setup-ha.yaml#L6) of `provisioning/setup-ha.yaml`
```yaml
    script: /opt/seagate/eos/hare/libexec/build-ees-ha
      - /var/lib/hare/cluster.yaml
      - /var/lib/hare/build-ees-ha-args.yaml
```
is not a valid YAML.

Solution: add missing `args:` line.
```yaml
    script: /opt/seagate/eos/hare/libexec/build-ees-ha
    args:
      - /var/lib/hare/cluster.yaml
      - /var/lib/hare/build-ees-ha-args.yaml
```
