### ISSUE TITLE
(Not really a) Problem: Hare does not support provisioner framework

### ISSUE THREAD

**Issue by rajanikantchirmade** [Seagate/cortx-hare#913]
_(This was reported in one of the meeting related to EOS on VM.
Though this is not a VM specific issue, thought to open a issue
to track and discuss at one place.)_

As per the [Provisioner framework][uniarch], every component has to export a “setup.yaml” file
that defines hooks, which can be invoked by Provisioner.  The intention is to prevent leaking of
the details of component's implementation into
[Provisioner code base](http://gitlab.mero.colo.seagate.com/eos/provisioner/ees-prvsnr/blob/dev/srv/components/hare/config.sls).

This file is already there in Hare repository.  We used it for M1, but when the Pacemaker-based HA solution
was introduced in M2, [hare's setup.yaml][] became a noop placeholder.

Proposed solution:

1. Refactor `hctl bootstrap` to extract cfgen part (hctl cfgen).
2. Update `setup.yaml`:
   ```yaml
   hare:
     post_install:
       script: null
       args: null
     init:
       script: hctl
       args: bootstrap --mkfs -c /var/lib/hare
     config:
       script: hctl
       args: cfgen -o /var/lib/hare /var/lib/hare/cluster.yaml
     test:
       script: hctl 
       args: test
     reset:
       script: null
       args: null
   ```

Related issue: #527 

[hare's setup.yaml]: https://github.com/Seagate/hare/blob/master/provisioning/setup.yaml
[uniarch]: https://seagatetechnology.sharepoint.com/:p:/r/sites/gteamdrv1/tdrive1224/Shared%20Documents/Components/Provisioning/Slide%20Decks/EOS%20Specifications%20for%20EESv1.pptx?d=w9cf1b2ada542405f92c9d7d77eb5599d&csf=1&web=1&e=220hfv&nav=eyJzSWQiOjI5MiwiY0lkIjowfQ
