### ISSUE TITLE
WIP: Problem:  Hare does not support provisioner framework

### ISSUE THREAD

**Issue by rajanikantchirmade** [Seagate/cortx-hare#914]
Support operations from setup.yaml.

As per provisioner framework every, components needs to write one file
setup.yaml. This is already here in Hare repository and we were using same
for M1. But while HA (pacemaker based) introduced, this file becomes empty.

Solution: (Proposed)

1. Refactor hctl bootstrap` to separate out only cfgen part (hctl cfgen).
2. Update setup.yaml

```
hare:
  post_install:
    script: null
    args: null
  init:
    script: hctl
    args: bootstrap --mkfs -c /var/lib/hare
  config:
    script: hctl
    args: cfgen -o /var/lib/hare /var/lib/hare/cluster.yaml
  test:
    script: hctl 
    args: test
  reset:
    script:
    args:
```

[ci skip]

Closes #913
